Algoritmo "ATIVIDADE 16"


Var

  ladoUm, ladoDois, Base : inteiro

Inicio

      Escreva("Digite a altura do primeiro lado: ")
      leia(ladoUm)
      
      Escreva("Digite a altura do segundo lado: ")
      leia(ladoDois)
      
      Escreva("Digite a largura da base")
      leia(Base)
      
      se (ladoUm) + (ladoDOis) > (Base)entao
      Escreval("Isso é um Triângundo")
      senao
      Escreval("Isso não é um Triângulo")
fimse


Fimalgoritmo