Algoritmo "ATIVIDADE 10"

Var

numeroUm, numeroDois, resultado : inteiro


Inicio
      Escreva ("Digite o Primeiro Número: ")
      Leia(numeroUm)
      
      Escreva ("Digite o Segundo Número :")
      Leia(numeroDOis)
      
      se (numeroUm > numeroDois) entao
       Escreval ("O número", numeroUm ," é maior que o", numeroDois)
      senao
      se (numeroUm = numeroDois) entao
      Escreval("O número", numeroUm ," é igual ao número dois")
      senao
     se(numeroUm < numeroDois)entao
      Escreval ("O numero", numeroUm ," é menor que o número dois")
      fimse
      fimse
      fimse
Fimalgoritmo
